The `+list+` subcommand is useful for finding out which packages have
available updates on the system.

[source,bash]
----
dnf list updates
----

[source,bash]
----
<< OUTPUT ABRIDGED >>
Available Upgrades
curl.x86_64          7.76.1-26.el9_3.3   rhel-9-for-x86_64-baseos-rpms
dbus.x86_64          1:1.12.20-8.el9     rhel-9-for-x86_64-baseos-rpms
dbus-common.noarch   1:1.12.20-8.el9     rhel-9-for-x86_64-baseos-rpms
<< OUTPUT ABRIDGED >>
----

Many packages on this system have updates available. Specifying a
package name with `+dnf update+` will constrain this operation to only
look for that package.

NOTE: If you instead want to make sure your entire system is up to
date, running `+dnf update+` without any other arguments apply updates
for all packages on your system (including YUM itself).

At the time of writing this lab, the *curl* package required an update.
Let’s update *curl*. Use the `+-y+` option to automatically say yes to
any prompts for the purposes of this lab.

Feel free to update any package listed.

[source,bash]
----
dnf -y update curl
----

[source,bash]
----
<< OUTPUT ABRIDGED >>
===============================================================
 Package     Arch    Version            Repository        Size
===============================================================
Upgrading:
 curl        x86_64  7.76.1-26.el9_3.3  rhel-9-for-x86_64-baseos-rpms   298 k
 libcurl     x86_64  7.76.1-26.el9_3.3  rhel-9-for-x86_64-baseos-rpms   286 k

Transaction Summary
===============================================================
Upgrade  2 Packages

<< OUTPUT ABRIDGED >>
----

NOTE: You sometimes see the subcommand `+upgrade+` being used somewhat
interchangeably with `+update+`. The difference between these two
subcommands is that `+upgrade+` will remove any obsolete packages from
the system. Often the configuration for DNF is such that these
subcommands will both carry out the `+upgrade+` operation.

== Removing a package

Removing a package follows the same theme of simplicity.

[source,bash]
----
dnf -y remove rhc
----

The extensive output shows you information about which dependent RPMs
were removed as part of this transaction.

[source,bash]
----
<< OUTPUT ABRIDGED >>
Removing:
 rhc                                x86_64  1:0.2.2-1.el9  @System  30 M
Removing dependent packages:
 redhat-cloud-client-configuration  noarch  1-10.el9       @System  6.5 k

<< OUTPUT ABRIDGED >>

Removed:
redhat-cloud-client-configuration-1-10.el9.noarch
rhc-1:0.2.2-1.el9.x86_64

Complete!
----

Use the `+list+` subcommand to confirm that the package has been
uninstalled:

[source,bash]
----
dnf list rhc
----

[source,bash]
----
<< OUTPUT ABRIDGED >>
Available Packages
rhc.x86_64  1:0.2.4-3.el9_3  rhel-9-for-x86_64-appstream-rpm
----

The package is now listed as _Available_ rather than _Installed_. The
next step will walk you through `+dnf history+` which provides some more
powerful tools for rolling back package transactions.
