The `+history+` subcommand provides a summary of recent `+dnf+`
transactions.

[source,bash]
----
dnf history
----

The output contains transaction IDs in the first column, which are how
you reference specific locations in the transaction history when
executing rollbacks.

[source,bash]
----
ID| Command                  | Date and time    | Action(s)| Altered
------------------------------------------------------------------
9 | remove rhc               | 2024-06-12 19:01 | Removed  | 2 EE
8 | update curl -y           | 2024-06-12 18:56 | Upgrade  | 2
7 | install -y wireshark     | 2024-06-12 18:45 | Install  | 197 EE
----

This subcommand is also useful for rolling back transactions if you
erroneously install or update a package, as it cleans up all of the
dependencies associated with the package. Rollback the state of your
system to before you uninstalled *httpd*:

[source,bash]
----
dnf -y history rollback 8
----

NOTE: The number 8 here is used here to specify that the rollback the
state of the system to how it was at transaction ID 8, or before you
removed *rhc*.

You can use other relative offsets, such as `+last-3+`, or you can use
absolute transaction IDs. For example, `+dnf history rollback 2+` would
rollback to the transaction where *rsync* was installed.

[source,bash]
----
<< OUTPUT ABRIDGED >>
Installed:
  redhat-cloud-client-configuration-1-10.el9.noarch
  rhc-1:0.2.2-1.el9.x86_64

Complete!
----

This command reinstalled the RPMs that are part of *rhc* (including
all dependencies), restoring the system state to how it was before the
previous transaction.

There are many more subcommands that you can use to customize how DNF
behaves. Check out this
https://access.redhat.com/sites/default/files/attachments/rh_yum_cheatsheet_1214_jcs_print-1.pdf[YUM
Command Cheat Sheet for RHEL] for more info.

NOTE: DNF and YUM are
syntactically identical. You can refer to the YUM cheat sheet for
subcommands that will all work with DNF.
